site_name: ML Note by UJHUYZ0110

theme: readthedocs

pages:
- Table of Content: 'index.md'
- Linear Models: 'linear_models.md'
- Support Vector Machines: 'support_vector_machines.md'
- Decision Trees: 'decision_trees.md'
- Ensemble Learning: 'ensemble_learning.md'
- Cost Functions: 'cost_functions.md'
- Metrics for Evaluation: 'metrics_for_evaluation.md'
- Gradient Descent: 'gradient_descent.md'

extra_javascript:
    - assets/mathjax_extra.js
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

python:
   version: 3 # for unicode
   setup_py_install: true
